Repository OtakuMap/OtakuWeb, pull requests merged in 2025-02, with the labels that each got.

#53 feat (issue #21) : MyPage 로그아웃, 프로필 이미지 변경 API 연동
  src/App.tsx
  src/api/common/upload-image.ts
  src/api/userInfo/logout.ts
  src/api/userInfo/profile_image.ts
  src/components/MyPage.tsx
  src/styles/category/category.styles.ts
  src/styles/common/Navbar.styles.ts
  src/types/common/image.ts
  src/types/userInfo/logout.ts
  src/types/userInfo/profile_image.ts
Labels: ✨ Feature, 🌈 FE

#55 feat(#54) hook분리, 새 페이지 UI 및 기능 구현, API 연동
  package.json
  src/App.tsx
  src/api/review/review.ts
  src/hooks/review/useRecentSearch.ts
  src/hooks/review/useReviewPage7.ts
  src/hooks/review/useSearchResult.ts
  src/hooks/review/useTopReviews.ts
  src/pages/EventPage2.tsx
  src/pages/ReviewPage1.tsx
  src/pages/ReviewPage2.tsx
  src/pages/ReviewPage4.tsx
  src/pages/ReviewPage5.tsx
  src/pages/ReviewPage7.tsx
  src/styles/event/EventPage2.styles.ts
  src/styles/review/ReviewPage.style.ts
  src/types/review/review.ts
Labels: 🔄 In Progress, ✨ Feature, 🌈 FE

#66 fix: 구글 Place API 사용량 초과 문제 해결
  index.html
  public/icon.svg
  src/api/map/routeLikes.ts
  src/components/map/LeftContainter.tsx
  src/components/map/LocationDetail.tsx
  src/components/map/MapContainer.tsx
  src/hooks/map/useSavedRoutes.ts
  src/styles/map/LeftContainer.styles.ts
  src/types/map/routeLikes.ts
  src/utils/mapUtils.ts
Labels: 🐛 Bug, 🌈 FE

#78 feat(#72, #77): 비밀번호 찾기 API , 비밀번호 변경 API 연동
  src/api/login/authAPI.ts
  src/pages/newsetpw.tsx
  src/pages/search_idpw.tsx
  src/types/login/auth.ts
Labels: ✨ Feature, 🐛 Bug, 🌈 FE

#93 eat(#48 ): Main 페이지 연동 시 커넥션 풀 에러 수정
  src/components/main/Main.tsx
  src/components/map/LocationDetail.tsx
  src/hooks/main/usePopularEvents.ts
  src/hooks/main/useTopReviews.ts
  src/pages/map/MapPage.tsx
  src/pages/map/RoutePage.tsx
  src/styles/map/LocationDetail.styles.ts
  src/utils/mapUtils.ts
Labels: 🐛 Bug, 🔥 High
