Repository OtakuMap/OtakuWeb, pull requests merged in 2025-01, with the labels that each got.

#3 feat: 구글 맵 기본 화면 및 검색 컴포넌트 구현 (#1)
  .eslintrc.json
  .gitignore
  .prettierrc
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/back.png
  src/assets/search_delete.png
  src/components/Cover.tsx
  src/components/RouteManagement.tsx
  src/components/common/BackButton.tsx
  src/components/common/Navbar.tsx
  src/components/common/Search.tsx
  src/components/map/FilterButton.tsx
  src/components/map/LeftContainter.tsx
  src/components/map/MapContainer.tsx
  src/index.css
  src/pages/map/MapPage.tsx
  src/styles/common/BackButton.styles.ts
  src/styles/common/Search.styles.ts
  src/styles/map/FilterButton.styles.ts
  src/styles/map/LeftContainer.styles.ts
  src/styles/map/MapContainer.styles.ts
  src/types/env.d.ts
  src/types/map/recommendation.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 👀 Review, ✨ Feature

#13 feat: 후기화면, 후기리스트 화면 구현
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/1.png
  src/assets/baseball.png
  src/assets/conan.png
  src/assets/profile2.png
  src/components/common/Navbar.tsx
  src/pages/ReviewPage1.tsx
  src/pages/ReviewPage2.tsx
  src/pages/ReviewPage3.tsx
  src/pages/ReviewPage4.tsx
  src/pages/ReviewPage5.tsx
  src/types/index.ts
Labels: 👀 Review, ✨ Feature

#8 feat: 로그인, 회원가입, ID PW 찾기, PW 수정 페이지 UI 구현(#4, #5, #6, #7)
  src/pages/newsetpw.tsx
Labels: 👀 Review, ✨ Feature

#19 Feature/koo
  package-lock.json
  package.json
  src/App.tsx
  src/assets/edit.png
  src/assets/pin.png
  src/components/map/LeftContainter.tsx
  src/components/map/MapContainer.tsx
  src/components/map/RouteLeftContainer.tsx
  src/main.tsx
  src/pages/map/MapPage.tsx
  src/pages/map/RoutePage.tsx
  src/styles/map/LeftContainer.styles.ts
  src/styles/map/RouteLeftContainer.styles.ts
  src/types/map/route.ts
Labels: 👀 Review, ✨ Feature

#24 Feat: 이벤트 상세 페이지 및 후기 작성 페이지
  src/App.tsx
  src/assets/2.png
  src/assets/3.png
  src/assets/Vector.png
  src/assets/backimage.png
  src/assets/event.png
  src/assets/eventImg.png
  src/assets/map.png
  src/assets/mapData.png
  src/assets/mapIcon.png
  src/assets/picture.png
  src/assets/product.png
  src/assets/profile3.png
  src/assets/review.png
  src/assets/reviewData.png
  src/pages/EventPage2.tsx
  src/pages/ReviewPage1.tsx
  src/pages/ReviewPage2.tsx
  src/pages/ReviewPage3.tsx
  src/pages/ReviewPage4.tsx
  src/pages/ReviewPage5.tsx
  src/pages/ReviewPage6.tsx
  src/pages/ReviewPage7.tsx
Labels: 🔄 In Progress, 👀 Review, ✨ Feature, 🌈 FE

#26 feat(#2 ): 디자인 추가된 부분 구현 및 경로, 장소 관련 컴포턴트 구현
  src/App.tsx
  src/assets/fav.png
  src/assets/fav2.png
  src/assets/next.png
  src/components/map/FilterButton.tsx
  src/components/map/LeftContainter.tsx
  src/components/map/LocationDetail.tsx
  src/components/map/MapContainer.tsx
  src/components/map/RouteDescriptionEditor.tsx
  src/components/map/RouteLeftContainer.tsx
  src/pages/map/MapPage.tsx
  src/pages/map/RoutePage.tsx
  src/styles/map/FilterButton.styles.ts
  src/styles/map/LeftContainer.styles.ts
  src/styles/map/LocationDetail.styles.ts
  src/styles/map/RouteDescriptionEditor.styles.ts
  src/types/map/place.ts
  src/types/map/route.ts
Labels: ✨ Feature

#32 Feat: 이벤트 및 후기 페이지에 기능 구현
  src/App.tsx
  src/assets/BackPage.png
  src/assets/NextPage.png
  src/assets/Polygon.png
  src/assets/StarEm.png
  src/assets/StarFull.png
  src/assets/dividerLine.png
  src/pages/EventPage2.tsx
  src/pages/ReviewPage4.tsx
  src/styles/event/EventPage2.styles.ts
Labels: 🔄 In Progress, ✨ Feature

#34 feat(#33) 일반 로그인 API 연동 및 API 연동 초기 세팅
  package-lock.json
  package.json
  src/App.tsx
  src/api/axios.ts
  src/api/login/authAPI.ts
  src/api/map/favorite.ts
  src/assets/event.png
  src/assets/map.png
  src/assets/review.png
  src/components/common/Search.tsx
  src/components/map/LeftContainter.tsx
  src/components/map/RouteLeftContainer.tsx
  src/hooks/login/useAuth.ts
  src/hooks/map/useFavoritePlaces.ts
  src/hooks/reduxHooks.ts
  src/pages/login.tsx
  src/store/auth/authSlice.ts
  src/store/index.ts
  src/styles/common/BackButton.styles.ts
  src/styles/common/Search.styles.ts
  src/styles/login/login.style.ts
  src/styles/map/FilterButton.styles.ts
  src/styles/map/LeftContainer.styles.ts
  src/styles/map/LocationDetail.styles.ts
  src/styles/map/RouteDescriptionEditor.styles.ts
  src/types/login/auth.ts
  src/types/map/favorite.ts
  src/utils/searchUtils.tsx
  src/utils/storage.ts
  src/utils/token.ts
  vite.config.ts
Labels: ✨ Feature, 🔥 High

#36 feat(#35) 이벤트 및 후기 페이지 기능 구현 완료
  src/assets/X.png
  src/pages/EventPage2.tsx
  src/pages/ReviewPage1.tsx
  src/pages/ReviewPage2.tsx
  src/pages/ReviewPage4.tsx
  src/pages/ReviewPage5.tsx
  src/pages/ReviewPage6.tsx
  src/styles/event/EventPage2.styles.ts
Labels: 🔄 In Progress, 👀 Review, ✨ Feature

#38 feat(#37): 회원가입 API 연동
  package-lock.json
  src/api/AuthenticationService.ts
  src/api/login/authAPI.ts
  src/assets/event.png
  src/assets/map.png
  src/assets/review.png
  src/components/Main.tsx
  src/components/MyPage.tsx
  src/components/RouteManagement.tsx
  src/components/SavedEvents.tsx
  src/components/SavedPlaces.tsx
  src/context/logincontext.tsx
  src/pages/Category.tsx
  src/pages/OAuthRedirect.tsx
  src/pages/login.tsx
  src/pages/login/OAuthRedirect.tsx
  src/pages/login/newsetpw.tsx
  src/pages/login/search_idpw.tsx
  src/pages/login/signup.tsx
  src/pages/newsetpw.tsx
  src/pages/signup.tsx
  src/styles/Category.css
  src/styles/Main.module.css
  src/types/login/auth.ts
  src/utils/debounce.ts
  src/utils/getOAuth.tsx
  src/utils/validate.ts
Labels: 🔄 In Progress, ✨ Feature, 🌈 FE

#40 fix: 로그인 시 userId 저장
  src/api/axios.ts
  src/api/login/authAPI.ts
  src/api/map/favorite.ts
  src/components/common/Navbar.tsx
  src/components/map/LeftContainter.tsx
  src/hooks/login/useAuth.ts
  src/hooks/map/useFavoritePlaces.ts
  src/store/auth/authSlice.ts
  src/styles/common/Navbar.styles.ts
  src/types/map/favorite.ts
  src/types/map/place.ts
  src/utils/token.ts
Labels: 👀 Review, 🐛 Bug

#42 feat(#41) 후기 페이지 및 이벤트 페이지 스타일 분리
  package-lock.json
  package.json
  src/App.tsx
  src/pages/ReviewPage1.tsx
  src/pages/ReviewPage2.tsx
  src/pages/ReviewPage3.tsx
  src/pages/ReviewPage4.tsx
  src/pages/ReviewPage5.tsx
  src/pages/ReviewPage6.tsx
  src/pages/ReviewPage7.tsx
  src/styles/review/ReviewPage.style.ts
Labels: 🔄 In Progress, 👀 Review, ✨ Feature, 🌈 FE
